// invitados.js
const invitados = [
  { id: 1, nombre: "Armando Palma", pases: 1 },
  { id: 2, nombre: "Armando Palma Y Familia", pases: 4 },
  { id: 3, nombre: "James Waldroup Y Familia", pases: 2 },
  { id: 4, nombre: "Hector Cabrera", pases: 1 },
  { id: 5, nombre: "Camilo Polo Y Familia", pases: 5 },
  { id: 6, nombre: "Raul Amaya Y Señora", pases: 2 },
  { id: 7, nombre: "Luis Amaya Y Familia", pases: 4 },
  { id: 8, nombre: "Leonel Amaya Y Familia", pases: 3 },
  { id: 9, nombre: "Juan Carlos Solorzano Y Familia", pases: 5 },
  { id: 10, nombre: "Marco Antonio Ruiz Y Familia", pases: 4 },
  { id: 11, nombre: "Alejandro Avila Y Señora", pases: 2 },
  { id: 12, nombre: "Marcos Avila E Hijo", pases: 2 },
  { id: 13, nombre: "Javier Escandon Y Familia", pases: 3 },
  { id: 14, nombre: "Orlando Rivas Y Señora", pases: 2 },
  { id: 15, nombre: "Alexis Rivas Y Familia", pases: 5 },
  { id: 16, nombre: "Jose Andres Rivas Y Familia", pases: 2 },
  { id: 17, nombre: "Jigme Balseiro Y Familia", pases: 4 },
  { id: 18, nombre: "Gustavo Gonzalez Y Familia", pases: 5 },
  { id: 19, nombre: "Carmela Illescas", pases: 1 },
  { id: 20, nombre: "Jesus Mayorga Y Familia", pases: 4 },
  { id: 21, nombre: "Alberto Morales Y Familia", pases: 4 },
  { id: 22, nombre: "David Boden Y Sra.", pases: 2 },
  { id: 23, nombre: "Francisco Boden Y Familia", pases: 3 },
  { id: 24, nombre: "Maria Boden", pases: 1 },
  { id: 25, nombre: "Antonio Mayorga Y Familia", pases: 4 },
  { id: 26, nombre: "Antonio Mayorga Y Sra.", pases: 2 },
  { id: 27, nombre: "Agustin Gamboa Y Familia", pases: 4 },
  { id: 28, nombre: "Rene Mijangos Y Sra.", pases: 2 },
  { id: 29, nombre: "Byron Lemus Y Sra.", pases: 2 },
  { id: 30, nombre: "Arne Mijangos Y Sra.", pases: 2 },
  { id: 31, nombre: "Christell Mijangos", pases: 1 },
  { id: 32, nombre: "Graciela Leon", pases: 1 },
  { id: 33, nombre: "Luis Alfonso Menocal, Sra. E Hijo", pases: 3 },
  { id: 34, nombre: "Pablo Echeverria", pases: 2 },
  { id: 35, nombre: "Luis Fernando Castro Y Sra.", pases: 2 },
  { id: 36, nombre: "Edgar Guerra", pases: 1 },
  { id: 37, nombre: "Danilo Gaytan Y Sra.", pases: 2 },
  { id: 38, nombre: "Edgardo Loukota Y Sra.", pases: 2 },
  { id: 39, nombre: "Hugo Muñoz", pases: 1 },
  { id: 40, nombre: "Ruben Garzaro", pases: 1 },
  { id: 41, nombre: "Jessica Castroconde", pases: 1 },
  { id: 42, nombre: "Vanessa Monzon", pases: 1 },
  { id: 43, nombre: "Berta Aldana", pases: 1 },
  { id: 44, nombre: "Alfredo Sulecio Y Sra.", pases: 2 },
  { id: 45, nombre: "Carlos Ordoñez Y Sra.", pases: 2 },
  { id: 46, nombre: "Edin Moran Y Sra.", pases: 2 },
  { id: 47, nombre: "Jorge Milian Y Sra.", pases: 2 },
  { id: 48, nombre: "Amilcar Concua Y Sra.", pases: 2 },
  { id: 49, nombre: "Eugenia Natareno", pases: 1 },
  { id: 50, nombre: "Maria Jose Figueroa", pases: 1 },
  { id: 51, nombre: "Carmen Natareno E Hijo", pases: 2 },
  { id: 52, nombre: "Leonel Rodas, Sra. E Hijo", pases: 3 },
  { id: 53, nombre: "Alvaro Morales Y Sra.", pases: 2 },
  { id: 54, nombre: "Daniel Leal Y Sra.", pases: 2 },
  { id: 55, nombre: "Jorge Garcia Y Sra.", pases: 2 },
  { id: 56, nombre: "Juan Manuel Velazco Y Sra.", pases: 2 },
  { id: 57, nombre: "Sebastian Herrera Y Sra.", pases: 2 },
  { id: 58, nombre: "Analilian Barrera", pases: 1 },
  { id: 59, nombre: "Roberto Barillas Y Sra.", pases: 2 },
  { id: 60, nombre: "Jorge Mario Monzon Y Sra.", pases: 2 },
  { id: 61, nombre: "Sr. Rulito Serrano", pases: 2 },
  { id: 62, nombre: "Sr. Javier Y Rosarito", pases: 2 },
  { id: 63, nombre: "Sr. Rafael Sánchez Y Sra.", pases: 3 },
  { id: 64, nombre: "Sra. Brenda Solis", pases: 1 },
  { id: 65, nombre: "Sr. Jose Rene Lira", pases: 2 },
  { id: 66, nombre: "Sra. Sandra Solis", pases: 1 },
  { id: 67, nombre: "Sr. Luis Pablo Noriega Y Familia", pases: 4 },
  { id: 68, nombre: "Sr. Carlos Hernández, Dharma Maldonado E Hijo", pases: 3 },
  { id: 69, nombre: "Sr. Alan Hernández", pases: 2 },
  { id: 70, nombre: "Srta. Sara Rosell", pases: 1 },
  { id: 71, nombre: "Sr. Rudy Ceballos Y Familia", pases: 0 },
  { id: 72, nombre: "Sr. Arturo Martinez Y Sra.", pases: 3 },
  { id: 73, nombre: "Sr. Francisco Quevedo Y Sra.", pases: 2 },
  { id: 74, nombre: "Sr. Mike España Y Sra.", pases: 2 },
  { id: 75, nombre: "Sr. Jose David Rueda", pases: 2 },
  { id: 76, nombre: "Sr. Rudy Herman Y Sra.", pases: 2 },
  { id: 77, nombre: "Sr. Luis Guillermo Perez Y Sra.", pases: 2 },
  { id: 78, nombre: "Sr. Andreas Lanz Y Sra.", pases: 3 },
  { id: 79, nombre: "Sr. Guillermo Kuhsie Y Novia", pases: 2 },
  { id: 80, nombre: "Sr. Rafael Anleu Y Sra.", pases: 2 },
  { id: 81, nombre: "Sr. Angel Ovalle, Sra. E Hijos", pases: 5 },
  { id: 82, nombre: "Sr. Jose Antonio Sr. Samayoa Y Sra.", pases: 2 },
  { id: 83, nombre: "Sr. Jorge Celada Y Sra.", pases: 2 },
  { id: 84, nombre: "Sr. Jose Antonio Jr. Samayoa Y Sra.", pases: 2 },
  { id: 85, nombre: "Sr. Roberto Samayoa Y Sra.", pases: 2 },
  { id: 86, nombre: "Sr. Fabian Luarca Y Sra.", pases: 2 },
  { id: 87, nombre: "Sr. Luis Pedro Sandoval, Sra. E Hijos", pases: 4 },
  { id: 88, nombre: "Sr. Roger Cifuentes Y Sra.", pases: 2 },
  { id: 89, nombre: "Sr. Jose Guillermo Gonzalez Y Sra.", pases: 2 },
  { id: 90, nombre: "Sr. Jose Luis Rueda Y Sra.", pases: 2 },
  { id: 91, nombre: "Sr. Carlos Alvarez Y Sra.", pases: 2 },
  { id: 92, nombre: "Sra. Maria Eugenia Cuellar", pases: 1 },
  { id: 93, nombre: "Sra. Idalia De Gonzales", pases: 1 },
  { id: 94, nombre: "Padre Anacleto Gaytan", pases: 1 },
  { id: 95, nombre: "Sr. William Mazariegos Y Sra.", pases: 2 },
  { id: 96, nombre: "Sr. Ajax Martinez Y Sra.", pases: 2 },
  { id: 97, nombre: "Sr. Enrique Arevalo Y Sra.", pases: 2 },
  { id: 98, nombre: "Sr. Alejandro Colon, Sra.", pases: 2 },
  { id: 99, nombre: "Sr. Jose Fernando Diez Y Sra.", pases: 2 },
  { id: 100, nombre: "Sr. Eduardo Gonzáles Y Sra.", pases: 2 },
  { id: 101, nombre: "Sr. Oscar Herrera Y Sra.", pases: 2 },
  { id: 102, nombre: "Padre Pancho", pases: 1 }
];
