// invitados.js
const invitados = [
  { id: 1, nombre: "Armando Palma", pases: 1 },
  { id: 2, nombre: "Armando Palma Y Familia", pases: 4 },
  { id: 3, nombre: "James Waldroup Y Familia", pases: 2 },
  { id: 4, nombre: "Hector Cabrera", pases: 1 },
  { id: 5, nombre: "Camilo Polo Y Familia", pases: 5 },
  { id: 6, nombre: "Raul Amaya Y Señora", pases: 2 },
  { id: 7, nombre: "Luis Amaya Y Familia", pases: 4 },
  { id: 8, nombre: "Leonel Amaya Y Familia", pases: 3 },
  { id: 9, nombre: "Juan Carlos Solorzano Y Familia", pases: 5 },
  { id: 10, nombre: "Marco Antonio Ruiz Y Familia", pases: 4 },
  { id: 11, nombre: "Alejandro Avila Y Señora", pases: 2 },
  { id: 12, nombre: "Marcos Avila E Hijo", pases: 2 },
  { id: 13, nombre: "Javier Escandon Y Familia", pases: 3 },
  { id: 14, nombre: "Orlando Rivas Y Señora", pases: 2 },
  { id: 15, nombre: "Alexis Rivas Y Familia", pases: 5 },
  { id: 16, nombre: "Jose Andres Rivas Y Familia", pases: 2 },
  { id: 17, nombre: "Jigme Balseiro Y Familia", pases: 4 },
  { id: 18, nombre: "Gustavo Gonzalez Y Familia", pases: 5 },
  { id: 19, nombre: "Carmela Illescas", pases: 1 },
  { id: 20, nombre: "Jesus Mayorga Y Familia", pases: 4 },
  { id: 21, nombre: "Alberto Morales Y Familia", pases: 4 },
  { id: 22, nombre: "David Boden Y Sra.", pases: 2 },
  { id: 23, nombre: "Francisco Boden Y Familia", pases: 3 },
  { id: 24, nombre: "Maria Boden", pases: 1 },
  { id: 25, nombre: "Antonio Mayorga Y Familia", pases: 4 },
  { id: 26, nombre: "Antonio Mayorga Y Sra.", pases: 2 },
  { id: 27, nombre: "Agustin Gamboa Y Familia", pases: 4 },
  { id: 28, nombre: "Rene Mijangos Y Sra.", pases: 2 },
  { id: 29, nombre: "Byron Lemus Y Sra.", pases: 2 },
  { id: 30, nombre: "Arne Mijangos Y Sra.", pases: 2 },
  { id: 31, nombre: "Christell Mijangos", pases: 1 },
  { id: 32, nombre: "Graciela Leon", pases: 1 },
  { id: 33, nombre: "Luis Alfonso Menocal, Sra. E Hijo", pases: 3 },
  { id: 34, nombre: "Pablo Echeverria", pases: 2 },
  { id: 35, nombre: "Luis Fernando Castro Y Sra.", pases: 2 },
  { id: 36, nombre: "Edgar Guerra", pases: 1 },
  { id: 37, nombre: "Danilo Gaytan Y Sra.", pases: 2 },
  { id: 38, nombre: "Edgardo Loukota Y Sra.", pases: 2 },
  { id: 39, nombre: "Hugo Muñoz", pases: 1 },
  { id: 40, nombre: "Ruben Garzaro", pases: 1 },
  { id: 41, nombre: "Jessica Castroconde", pases: 1 },
  { id: 42, nombre: "Vanessa Monzon", pases: 1 },
  { id: 43, nombre: "Berta Aldana", pases: 1 },
  { id: 44, nombre: "Alfredo Sulecio Y Sra.", pases: 2 },
  { id: 45, nombre: "Carlos Ordoñez Y Sra.", pases: 2 },
  { id: 46, nombre: "Edin Moran Y Sra.", pases: 2 },
  { id: 47, nombre: "Jorge Milian Y Sra.", pases: 2 },
  { id: 48, nombre: "Amilcar Concua Y Sra.", pases: 2 },
  { id: 49, nombre: "Eugenia Natareno", pases: 1 },
  { id: 50, nombre: "Maria Jose Figueroa", pases: 1 },
  { id: 51, nombre: "Carmen Natareno E Hijo", pases: 2 },
  { id: 52, nombre: "Leonel Rodas, Sra. E Hijo", pases: 3 },
  { id: 53, nombre: "Alvaro Morales Y Sra.", pases: 2 },
  { id: 54, nombre: "Daniel Leal Y Sra.", pases: 2 },
  { id: 55, nombre: "Jorge Garcia Y Sra.", pases: 2 },
  { id: 56, nombre: "Juan Manuel Velazco Y Sra.", pases: 2 },
  { id: 57, nombre: "Sebastian Herrera Y Sra.", pases: 2 },
  { id: 58, nombre: "Analilian Barrera", pases: 1 },
  { id: 59, nombre: "Roberto Barillas Y Sra.", pases: 2 },
  { id: 60, nombre: "Jorge Mario Monzon Y Sra.", pases: 2 },
  { id: 61, nombre: "Padre Pancho", pases: 1 }
];
