// invitados.js
const invitados = [
  { id: 1, nombre: "Armando Palma", pases: 1 },
  { id: 2, nombre: "Armando Palma Y Familia", pases: 4 },
  { id: 3, nombre: "James Waldroup Y Familia", pases: 2 },
  { id: 4, nombre: "Hector Cabrera", pases: 1 },
  { id: 5, nombre: "Camilo Polo Y Familia", pases: 5 },
  { id: 6, nombre: "Raul Amaya Y Señora", pases: 2 },
  { id: 7, nombre: "Luis Amaya Y Familia", pases: 4 },
  { id: 8, nombre: "Leonel Amaya Y Familia", pases: 3 },
  { id: 9, nombre: "Juan Carlos Solorzano Y Familia", pases: 5 },
  { id: 10, nombre: "Marco Antonio Ruiz Y Familia", pases: 4 },
  { id: 11, nombre: "Alejandro Avila Y Señora", pases: 2 },
  { id: 12, nombre: "Marcos Avila E Hijo", pases: 2 },
  { id: 13, nombre: "Javier Escandon Y Familia", pases: 3 },
  { id: 14, nombre: "Orlando Rivas Y Señora", pases: 2 },
  { id: 15, nombre: "Alexis Rivas Y Familia", pases: 5 },
  { id: 16, nombre: "Jose Andres Rivas Y Familia", pases: 2 },
  { id: 17, nombre: "Jigme Balseiro Y Familia", pases: 4 },
  { id: 18, nombre: "Gustavo Gonzalez Y Familia", pases: 5 },
  { id: 19, nombre: "Carmela Illescas", pases: 1 },
  { id: 20, nombre: "Jesus Mayorga Y Familia", pases: 4 },
  { id: 21, nombre: "Alberto Morales Y Familia", pases: 4 },
  { id: 22, nombre: "David Boden Y Sra.", pases: 2 },
  { id: 23, nombre: "Francisco Boden Y Familia", pases: 3 },
  { id: 24, nombre: "Maria Boden", pases: 1 },
  { id: 25, nombre: "Antonio Mayorga Y Familia", pases: 4 },
  { id: 26, nombre: "Antonio Mayorga Y Sra.", pases: 2 },
  { id: 27, nombre: "Agustin Gamboa Y Familia", pases: 4 },
  { id: 28, nombre: "Rene Mijangos Y Sra.", pases: 2 },
  { id: 29, nombre: "Byron Lemus Y Sra.", pases: 2 },
  { id: 30, nombre: "Arne Mijangos Y Sra.", pases: 2 },
  { id: 31, nombre: "Christell Mijangos", pases: 1 },
  { id: 32, nombre: "Graciela Leon", pases: 1 },
  { id: 33, nombre: "Luis Alfonso Menocal, Sra. E Hijo", pases: 3 },
  { id: 34, nombre: "Pablo Echeverria", pases: 2 },
  { id: 35, nombre: "Luis Fernando Castro Y Sra.", pases: 2 },
  { id: 36, nombre: "Edgar Guerra", pases: 1 },
  { id: 37, nombre: "Danilo Gaytan Y Sra.", pases: 2 },
  { id: 38, nombre: "Edgardo Loukota Y Sra.", pases: 2 },
  { id: 39, nombre: "Hugo Muñoz", pases: 1 },
  { id: 40, nombre: "Ruben Garzaro", pases: 1 },
  { id: 41, nombre: "Jessica Castroconde", pases: 1 },
  { id: 42, nombre: "Vanessa Monzon", pases: 1 },
  { id: 43, nombre: "Berta Aldana", pases: 1 },
  { id: 44, nombre: "Alfredo Sulecio Y Sra.", pases: 2 },
  { id: 45, nombre: "Carlos Ordoñez Y Sra.", pases: 2 },
  { id: 46, nombre: "Edin Moran Y Sra.", pases: 2 },
  { id: 47, nombre: "Jorge Milian Y Sra.", pases: 2 },
  { id: 48, nombre: "Amilcar Concua Y Sra.", pases: 2 },
  { id: 49, nombre: "Eugenia Natareno", pases: 1 },
  { id: 50, nombre: "Maria Jose Figueroa", pases: 1 },
  { id: 51, nombre: "Carmen Natareno E Hijo", pases: 2 },
  { id: 52, nombre: "Leonel Rodas, Sra. E Hijo", pases: 3 },
  { id: 53, nombre: "Alvaro Morales Y Sra.", pases: 2 },
  { id: 54, nombre: "Daniel Leal Y Sra.", pases: 2 },
  { id: 55, nombre: "Jorge Garcia Y Sra.", pases: 2 },
  { id: 56, nombre: "Juan Manuel Velazco Y Sra.", pases: 2 },
  { id: 57, nombre: "Sebastian Herrera Y Sra.", pases: 2 },
  { id: 58, nombre: "Analilian Barrera", pases: 1 },
  { id: 59, nombre: "Roberto Barillas Y Sra.", pases: 2 },
  { id: 60, nombre: "Jorge Mario Monzon Y Sra.", pases: 2 },
  { id: 61, nombre: "Padre Pancho", pases: 1 },
  { id: 62, nombre: "Sasha Garcia", pases: 1 },
  { id: 63, nombre: "Gian Carlo Grajeda", pases: 1 },
  { id: 64, nombre: "Emiliano Bardales", pases: 1 },
  { id: 65, nombre: "Mario Cano", pases: 1 },
  { id: 66, nombre: "Rodrigo Perez", pases: 1 },
  { id: 67, nombre: "Camila Hernandez", pases: 1 },
  { id: 68, nombre: "Maria Paula Ordoñez", pases: 1 },
  { id: 69, nombre: "Camila Moran", pases: 1 },
  { id: 70, nombre: "Ximena Flores", pases: 1 },
  { id: 71, nombre: "Valentina Milian", pases: 1 },
  { id: 72, nombre: "Valentina Matias", pases: 1 },
  { id: 73, nombre: "Ariana Concua", pases: 1 },
  { id: 74, nombre: "Camila Martinez", pases: 1 },
  { id: 75, nombre: "Sophia Rosales", pases: 1 },
  { id: 76, nombre: "Mia Suarez", pases: 1 },
  { id: 77, nombre: "Jose Mario Monzon", pases: 1 },
  { id: 78, nombre: "Pablo Monzon", pases: 1 },
  { id: 79, nombre: "Luciana Garcia", pases: 1 },
  { id: 80, nombre: "Daniela Barillas", pases: 1 },
  { id: 81, nombre: "Adriana Velazco", pases: 1 },
  { id: 82, nombre: "Crystal Garcia", pases: 1 },
  { id: 83, nombre: "Juan Diego Yela", pases: 1 },
  { id: 84, nombre: "Alejandro Yela", pases: 1 },
  { id: 85, nombre: "Valentina Yela", pases: 1 },
  { id: 86, nombre: "Italo Donis", pases: 1 },
  { id: 87, nombre: "Ricardo Reyes", pases: 1 },
  { id: 88, nombre: "Jose Daniel Chapas", pases: 1 },
  { id: 89, nombre: "Sofia Chapas", pases: 1 },
  { id: 90, nombre: "Mariandrea Chapas", pases: 1 },
  { id: 91, nombre: "Esteban Soto", pases: 1 },
  { id: 92, nombre: "Gena Munguia", pases: 1 },
  { id: 93, nombre: "Barbara Carlos", pases: 1 },
  { id: 94, nombre: "Maria Lourdes", pases: 1 },
  { id: 95, nombre: "Daniela Morzan", pases: 1 },
  { id: 96, nombre: "Cecilia Reyes", pases: 1 },
  { id: 97, nombre: "Jimena Sanchez", pases: 1 },
  { id: 98, nombre: "Lucia Jimenez", pases: 1 },
  { id: 99, nombre: "Luis Gerardo Monrroy", pases: 1 },
  { id: 100, nombre: "Jose Daniel Garcia", pases: 1 },
  { id: 101, nombre: "Andres Mendez", pases: 1 },
  { id: 102, nombre: "Juan Diego Camacho", pases: 1 },
  { id: 103, nombre: "Daphne", pases: 1 },
  { id: 104, nombre: "Javier Velasquez", pases: 1 },
  { id: 105, nombre: "Daniela Rios", pases: 1 },
  { id: 106, nombre: "Camila Benavente", pases: 1 },
  { id: 107, nombre: "Diana Marquez", pases: 1 },
  { id: 108, nombre: "Juan Diego Velazco", pases: 1 },
  { id: 109, nombre: "Carmen Lucia Velazco", pases: 1 },
  { id: 110, nombre: "Samantha Herrera", pases: 1 },
  { id: 111, nombre: "Melissa Herrera", pases: 1 },
  { id: 112, nombre: "Diego Maldonado", pases: 1 },
  { id: 113, nombre: "Daniela Leal", pases: 1 },
  { id: 114, nombre: "Sofia Leal", pases: 1 },
  { id: 115, nombre: "Rodrigo Catalan", pases: 1 },
  { id: 116, nombre: "Juan Arana", pases: 1 },
  { id: 117, nombre: "Daniela Valenzuela", pases: 1 },
  { id: 118, nombre: "Gabriel Garcia", pases: 1 },
  { id: 119, nombre: "Sofia Mejia", pases: 1 },
  { id: 120, nombre: "Maria Rene Rodas", pases: 1 },
  { id: 121, nombre: "Jimena Morales", pases: 1 },
  { id: 122, nombre: "Ninoshka Salguero", pases: 1 },
  { id: 123, nombre: "Mia Contreras", pases: 1 },
  { id: 124, nombre: "Marcela Guzman", pases: 1 },
  { id: 125, nombre: "Marisabel Aguilar", pases: 1 },
  { id: 126, nombre: "Valery Camacho", pases: 1 },
  { id: 127, nombre: "Matias Grajeda", pases: 1 },
  { id: 128, nombre: "Lionel Lobos", pases: 1 },
  { id: 129, nombre: "Esther Fuentes", pases: 1 },
  { id: 130, nombre: "Camila Caceros", pases: 1 },
  { id: 131, nombre: "Mia Pinto", pases: 1 },
  { id: 132, nombre: "Jose Angel Juarez", pases: 1 },
  { id: 133, nombre: "Martin Saldarriaga", pases: 1 },
  { id: 134, nombre: "Anika Sosa", pases: 1 },
  { id: 135, nombre: "Danika Dubon", pases: 1 },
  { id: 136, nombre: "Valeria Melendez", pases: 1 },
  { id: 137, nombre: "Valentina Moreira", pases: 1 },
  { id: 138, nombre: "Charlotte Orellana", pases: 1 },
  { id: 139, nombre: "Maria Andrea Del Pilar Perez", pases: 1 },
  { id: 140, nombre: "Andrea Chacon", pases: 1 },
  { id: 141, nombre: "Pedro Garcia", pases: 1 },
  { id: 142, nombre: "Melanie Del Val", pases: 1 },
  { id: 143, nombre: "Camila Jerez", pases: 1 },
  { id: 144, nombre: "Mia Lopez", pases: 1 },
  { id: 145, nombre: "Sofia Lopez", pases: 1 },
  { id: 146, nombre: "Fabrizio Grazioso", pases: 1 },
  { id: 147, nombre: "Jose Gabriel Santos", pases: 1 },
  { id: 148, nombre: "Tania Guzman", pases: 1 },
  { id: 149, nombre: "Andrea Estrada", pases: 1 },
  { id: 150, nombre: "Mathew Prado", pases: 1 },
  { id: 151, nombre: "Luis Fernando Lima", pases: 1 },
  { id: 152, nombre: "Pedro Mazariegos", pases: 1 },
  { id: 153, nombre: "Diego Antillon", pases: 1 },
  { id: 154, nombre: "Jose Carlos Orellana", pases: 1 },
  { id: 155, nombre: "Byron Salvatierra", pases: 1},
  { id: 156, nombre: "Valeria García", pases: 1 },
  { id: 157, nombre: "Fernando Osorio y Sra.", pases: 2 },
  { id: 158, nombre: "Fernando Osorio Reyes e hijo", pases: 2 },
  { id: 159, nombre: "Natalia Sahagun", pases: 1 },
  { id: 160, nombre: "Natalia Muñoz", pases: 1 },
  { id: 161, nombre: "Treyci García", pases: 2 },
  { id: 162, nombre: "María Boden", pases: 2 },
  { id: 163, nombre: "Ángel Peña", pases: 1 },
  { id: 164, nombre: "⁠Natalia Leonardo", pases: 1},
  { id: 165, nombre: "⁠Diego Gómez", pases: 1}
];
